#----------------------
# author:	maoshuai
# date:		2021-02-18
# desc:     The main method of app with basic module support: log and profile
#----------------------

importModule 'profile' "true"
# Note: log module should be imported after profile
importModule 'log'
importModule 'job'


app_main(){

    # start job
    job_startJob "$@"

    # Note: DON'T add any lines afterwards, or the return code will be tampered!
}