#----------------------
# author:	maoshuai
# date:		2020-04-26
# desc:     dispatch a job to a handler
#----------------------

importModule 'log'
importModule 'lock'
importModule 'git'

job_startJob(){

     # refresh log name by job name immediately
    job_refreshLogName "$@"
    
    # set log mdc
    logSetMDC "MSHELL_JOB_ID" "$(job_generateJobId)"
    logSetMDC "MSHELL_JOB_NAME" "$1"

    # print banner and version related info
    _job_printExtraInfo "$MSHELL_APP_BANNER"
    local gitCommit="$(git_getCommitAbbrev)"
    local gitBuildTime="$(git_getBuildTime)"
    local installTime="$(git_getInstallTime)"
    _job_printExtraInfo "(commit: $gitCommit, build: $gitBuildTime, install: $installTime)"
    _job_printExtraInfo ""

    # check parameters and get jobName
	if [ $# -lt 1 ];then
		throw "No job name."
	fi
    local jobName="$1"
    shift 1

    # print job basic info
    local jobBeginTime=$(date +%s)
	local jobBeginTimeHumanReadable="$(date -d @${jobBeginTime} "+%Y-%m-%d %H:%M:%S")"
    _job_printExtraInfo "[JOB_INFO]
- Job Name      : $jobName
- Job Args      : $@
- Staring Time  : $jobBeginTimeHumanReadable
- PID           : $$
- Shell Logging : $(_getCurrentLogFile)
"

    # dipatch the job to the handler
    _job_printExtraInfo "[JOB_BEGIN]>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>>"
    # here is a trick to fix set -e problem
    set +e
	_job_dispatch "$jobName" "$@" 
    local exitCode=$?
    set -e
    _job_printExtraInfo "[JOB_END  ]<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<"



    # job is finished, print the summary info.
    local jobEndTime=$(date +%s)
	local jobEndTimeHumanReadable="$(date -d @${jobEndTime} "+%Y-%m-%d %H:%M:%S")"
	local jobCostTime=$(($jobEndTime - $jobBeginTime))

    # print exit code 
    local exitFlag="FAILED"
	if [ $exitCode -eq 0 ];then
		exitFlag="SUCCESSFUL"
	fi

	_job_printExtraInfo "
[EXIT_STATUS]
- End Time  : $jobEndTimeHumanReadable
- Cost Sec  : $jobCostTime
- Exit Code : $exitCode ($exitFlag)"
    
    return $exitCode
   
}

# why use & and wait?
# note: set -e is ignored in sub-shell
_job_dispatch(){
    _job_doDispatch "$@" &
    wait $!
}

_job_doDispatch(){
    set -e
    local handler="$1"
    shift 1
    
    # get lock for this job
    lock_acquireLock "$handler"

    # get handler shell
    local handlerPath="$MSHELL_HOME/handler/$handler"

    logInfo "Dispatch to handler: $handlerPath"

    if [ ! -f $handlerPath ];then
        logEchoError "No such handler: $handlerPath"
        return 1
    fi

    # source the handler then call handler_main if possible.
    . $handlerPath

    if [ x"$(type -t "handler_main")" == x"function" ];then
        handler_main "$@"
    else
        logWarn "Running ordinary shell, it is highly recommended to convert it to a handler!"
    fi
  

}

job_refreshLogName(){
    local jobName="$1"
    jobName=$(echo "$jobName" | sed 's@/@__@g')
    # each job has its own log file
    if [ x"$jobName" != x"" ];then
        refreshLogger "$jobName"
    else
        refreshLogger "no_name_job"
    fi
}

# generate a uniq job id
job_generateJobId(){
	date +%Y%m%d%H%M%S%N
}


_job_printExtraInfo(){
    if [ x"$MSHELL_JOB_PRINT_VERBOSE" == x"true" ];then
        logEcho "$@"
    else
        logInfo "$@"
    fi
}